### ISSUE TITLE
Page - home page and transferred certificate

### ISSUE THREAD

**Issue by raysummee** [Megabyte-143/certified_cliche#18]
## Page - home page and transferred certificate
tracking in #15 

### description:
Create home page for the organisation flow. Which will contain unique certificate and events/ groups. 
Please refer to the Figma file

### Figma page name:
* 3.home page
* 7.transferred certificate

(both are the same page with different functionality)

### The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

**Comment by mishra811** [comment]
Hey can you please assign me this issue to work on.

**Comment by raysummee** [comment]
@mishra811 I have assigned you this issue. You may start working it now. All the best.

**Comment by raysummee** [comment]
@mishra811 What is your progress in this. If you have any doubt feel free to ask.

**Comment by mishra811** [comment]
Yes actually I was not familiar with nextjs 
So I was learning it . But I started working on the issue.

One doubt though 
Should I use pure css or tailwind for the components
