### ISSUE TITLE
Page - Received Certificate

### ISSUE THREAD

**Issue by raysummee** [Megabyte-143/certified_cliche#26]
## Page - Received Certificate
tracking in #15 

### description:
This page is to show all the certificate of participates

### Figma page name:
* 9.received certificate

(both are the same page with different functionality)

### The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

**Comment by Abhinav0909** [comment]
Hey,This sounds interesting .I want to work on this issue

**Comment by raysummee** [comment]
@Abhinav0909 I can see you commented almost all of the issues. I'm afraid, but I cannot assign all of the issue to you. Please select any one of the issue for now. Then I can assign it to you. Start working on the issue and complete it. After that I can assign you the other one and so. Thank you for cooperating.

**Comment by SaachiKaup** [comment]
Hello @raysummee!
If the issue is still open, could I work on it? Wanted to contribute to this project!
Regards,
GSSOC'22 participant

**Comment by codewhen** [comment]
@SaachiKaup Sure you can definitely work on this.

I have assigned you this issue. You may start working on this now. All the best and thank you for your kind contribution.

**Comment by SaachiKaup** [comment]
Thank you!

**Comment by SaachiKaup** [comment]
Hello @raysummee !
Project is setup for now! Do I have to give you updates here or on discord?
Regards,
Saachi!

**Comment by codewhen** [comment]
@SaachiKaup  You can give your updates either here or in the discord channel. If you need any help or have any doubt, feel free to ask.

**Comment by SaachiKaup** [comment]
Hello @raysummee ! I tried to access the Polygon Mumbai network but I am getting an error saying my funds are insufficient. Is there a particular limit that I am not aware of?
![image](https://user-images.githubusercontent.com/87465689/167077403-4ec93a09-eef5-41cd-8085-cc13f5279b5a.png)

**Comment by codewhen** [comment]
@SaachiKaup please use localhost for the hardhat for now. Meanwhile we'll check if there is any issue deploying to mumbai test net.

**Comment by SaachiKaup** [comment]
Alright thank you!
