### ISSUE TITLE
Different styles of writing CSS 

### ISSUE THREAD

**Issue by Rajdip019** [Megabyte-143/certified_cliche#34]
**Describe the bug**
In the code some of the CSS is written in CSS sheets. Some of them are in inline using style tag and some of them are in Tailwind CSS. This causes problem for the developers where to find which CSS.

**Expected behaviour**
Should only use one style.

Can I change all the CSS to Tailwind and also add some utility classes to improve development experience?

**Comment by raysummee** [comment]
@Rajdip019 we are in the road map of implementing new UI from the design. So Every UI part has to be redone. So the old UI styling is not an issue here. Hope I could solve your doubt. 

I'll close this issue. If you like to reopen it, let me know. 
Thank you.
