### ISSUE TITLE
Component - NFT Cards

### ISSUE THREAD

**Issue by Rajdip019** [Megabyte-143/certified_cliche#47]
**Describe the bug**
The card is not a component although it will be used the multiple times in the website. 

**Expected behaviour**
The card should be component.

I would love to work on this.

**Comment by raysummee** [comment]
Thank you for pointing this out. I'll add this into the main task.

**Comment by raysummee** [comment]
### Components - NFT Cards
tracking in #15 

- The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

#### Figma Link: [click here](https://www.figma.com/file/HjYi7KbugT0xsXoA7arIN2/Untitled?node-id=0%3A1)

**Comment by raysummee** [comment]
@Rajdip019  you can assign it to you. You may start working on it now.

**Comment by Rajdip019** [comment]
Thanks will start working on this today.

**Comment by raysummee** [comment]
@Rajdip019 Please use params to get the title and description of the NFT in NFT Cards. The values should be pass from parent component.

**Comment by Rajdip019** [comment]
I have used props to pass all info from parent to the component. @raysummee
