### ISSUE TITLE
Replace all the Current NFT Card to the New Component. 

### ISSUE THREAD

**Issue by Rajdip019** [Megabyte-143/certified_cliche#50]
**Describe the bug**
Change all the Current Card Code to the New Component. Here is a image of that. And pass props to display data.

![Screenshot 2022-03-02 233509](https://user-images.githubusercontent.com/91758830/156425891-5c04cab6-fc99-4ff2-9b89-80d3141353a6.jpg)

**Additional context**
I would love to work on this!

**Comment by raysummee** [comment]
@Rajdip019 This would come under the existing issue #47 (Component - NFT Cards). Please update that PR #49 too with these changes. You can commit on that branch, which will automatically add new changes to that PR. I'll update the issue there too. I'm closing this issue now.
