### ISSUE TITLE
Automate the editing of addresses in `config.js` file

### ISSUE THREAD

**Issue by Megabyte-143** [Megabyte-143/certified_cliche#54]
**Description**
=> As mentioned in the [README](https://github.com/Megabyte-143/certified_cliche/blob/main/README.md), you have to paste the addresses, `nftAddress` and `nftTransferAddress` from the terminal **after deploying** the contract on LOCAL HOST or on TESTNET.

**TASK**
=> Automate the editing of the `config.js` file in `CONTRACT` directory. 

**Image for reference from the [README](https://github.com/Megabyte-143/certified_cliche/blob/main/README.md)**

![Image for reference](https://user-images.githubusercontent.com/79016290/156495538-b5cb6ca2-7909-47bc-9822-7f944e6f7541.png)

**Comment by Tarun-k-Gupta** [comment]
I would like to work on this issue.

**Comment by Megabyte-143** [comment]
Sure. 

**Note**=> Submission deadline is in 1 day as it is a Level 1 issue.
