### ISSUE TITLE
Component: Event/Groups Card

### ISSUE THREAD

**Issue by Rajdip019** [Megabyte-143/certified_cliche#55]
**Describe the bug**
There is events/group component in the figma file, which is there in  the many pages and should be a component.

**Expected behaviour**
The event/group card should be a component.

**Additional context**
I would love to work on this.

**Comment by raysummee** [comment]
@Rajdip019 Thank you for pointing this out. I will add this to main issue for tracking.

**Comment by raysummee** [comment]
### Components - Event/Groups
tracking in #15 

description:
Create the large card in event/group, which contains the name, image, description of the clicked/browsed event

- The folder should be like follows:
 js: components/components-name/components-name.js
 css: components/components-name/components-name.module.css

#### Figma Link: [click here](https://www.figma.com/file/HjYi7KbugT0xsXoA7arIN2/Untitled?node-id=0%3A1)
