### ISSUE TITLE
Convert EXCEL to JSON Function

### ISSUE THREAD

**Issue by Megabyte-143** [Megabyte-143/certified_cliche#56]
**Description** 
=> 
- We will be accepting the **Excel sheet** which can be in any format _XLS_ or _XLSX_ format from the user. 
- The Sheet will contain the following attributes initially :-
_(Name, Description, ImageUrl, Receiver Address)_
- We have to get this data in the **JSON** format so that we can upload it to the IPFS.

**Task**
=>
Make a function in the `client` directory in a separate directory `utils` in a file named `excelToJSON.js`, which will accept the Excel Sheet and convert it into the JSON Format. 

You may refer [here](https://stackoverflow.com/questions/28782074/excel-to-json-javascript-code) for some guidance.

**Comment by Karan11000** [comment]
I want to work on this issue under Gssoc 2022. Can you assign it to me

**Comment by raysummee** [comment]
@Karan11000 I have assigned you this issue. You can start working on this now. All the best.

**Comment by Karan11000** [comment]
Hey Can you please also provide some test examples.

**Comment by Megabyte-143** [comment]
Hi @Karan11000,  I have provided a reference for the help. It would be great for you if you try to get this done without any other help. 
If you are not able to complete it then PING US, we provide you some other resources.

Thanks for contributing
_Megabyte_
