### ISSUE TITLE
Make `Hardhat` tests for testing the SMART CONTRACTS

### ISSUE THREAD

**Issue by Megabyte-143** [Megabyte-143/certified_cliche#64]
**Description**
=> Smart Contracts are immutable hence they needed to be test thoroughly to avoid any type of security breaches after deployment.

**Task**
=> Write all the test cases possible to test both `NFT.sol` and `NFTTransfer.sol` smart contract in **_CONTRACT/test/sample-test.js_**

**Comment by Tarun-k-Gupta** [comment]
I would like to take up this issue.

**Comment by raysummee** [comment]
@Tarun-k-Gupta I have assigned you this issue. You may start working in this now.
