### ISSUE TITLE
Improving the Navbar and Title of the website

### ISSUE THREAD

**Issue by Shweta597** [Megabyte-143/certified_cliche#66]
**Describe the solution you'd like**

I want to add website name as the title of the page and also create a navbar in which the name of the website will be on left part and other navbar item would be on right side to make it more presentable

**Comment by Shweta597** [comment]
I would like to work on this issue under GSSOC'22

**Comment by raysummee** [comment]
@Shweta597 I thank you for pointing out this idea. but we already have a similar issue on the roadmap ( #16 ). I'm closing this issue for now. Please let me know if you have any doubt.
