### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by mishra811** [Megabyte-143/certified_cliche#69]
In the project README it's written that 

Uncomment the LocalHost provider in `client/pages/index.js`

```
 const provider = new ethers.providers.JsonRpcProvider();
```

But this line of code is not in `client/pages/index.js`

It is actually in `client/pages/home.js` on line 34

**Comment by raysummee** [comment]
@mishra811 Thank you for pointing this out.

**Comment by mishra811** [comment]
Can you assign me this issue?

**Comment by megabyte0x** [comment]
@mishra811 would you like to work on this issue ?

**Comment by 0xMishra** [comment]
Sure

**Comment by megabyte0x** [comment]
@mishra811 any updates ?

**Comment by 0xMishra** [comment]
Yes raised a PR regarding this 
Please check
